### ISSUE TITLE
在C#中使用依赖注入-三层结构

### ISSUE THREAD

**Issue by newbe36524** [newbe36524/Newbe.Docs#124]
/Use-Dependency-Injection/Simple-Three-Layers/

**Comment by meesii** [comment]
Autofac不知道能不能突破AppDoMain的限制

**Comment by newbe36524** [comment]
> Autofac不知道能不能突破AppDoMain的限制

不能的，几乎的IOC框架都不能，跨Domain通信一般都是自己处理。不过Autofac可以支持多租户模式，可以理解为多容器
