### ISSUE TITLE
Newbe・简历 | Newbe

### ISSUE THREAD

**Issue by newbe36524** [newbe36524/Newbe.Docs#159]
https://www.newbe.pro/resume/ 

 Newbe便是新生，唯有不断蜕变才能焕然新生。概要俞坤，男，92年生，2015年6月本科毕业于福建师范大学，计算机科学与技术专业。五年专注于.Net 服务端开发 / BS系统开发。三年担任开发组长或开发经理。除了自身具备很强的编码能力、文档能力、表达能力之外，同时具备一定的技术管理能力，能够胜任决策技术要点、组织团队工作、团队计划制定等等技术管理工作。开源项目作者，独立开发实现的“QQ机器人框架-

**Comment by rootindark** [comment]
优秀！

**Comment by feisun001** [comment]
考虑来南昌上班不

**Comment by newbe36524** [comment]
> 考虑来南昌上班不

从未去过的地方~
