### ISSUE TITLE
跨境电商 iHerb 上海职位内推

### ISSUE THREAD

**Issue by newbe36524** [newbe36524/Newbe.Docs#164]
/Others/Internal-recommendation-Of-iHerb/

**Comment by CheungDB** [comment]
博主，netcore 2.2好像不是长期支持版本，可以考虑升级到netcore 3.1

**Comment by newbe36524** [comment]
> @CheungDB
> 博主，netcore 2.2好像不是长期支持版本，可以考虑升级到netcore 3.1

你说的对，现在用的是 2.1 LTS 后面会升 3.1

**Comment by YanZhiwei** [comment]
.Net岗位还招聘吗？

**Comment by newbe36524** [comment]
> .Net岗位还招聘吗？

有的，朋友，还有很多

**Comment by lqlive** [comment]
英语是硬性要求吗？

**Comment by newbe36524** [comment]
> @endless001
> 英语是硬性要求吗？

听、读、写，肯定是没有办法避免的，说的话就看想要达到的职级了。

**Comment by zhujinhu21** [comment]
工作用英语交流吗

**Comment by newbe36524** [comment]
> 工作用英语交流吗

看什么职级，普通的开发，需要读写听。更高的职级则需要说。
